import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Mariem',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin : true,
    },
    {
      name: 'Houssem',
      email: 'users@exemple.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin : false,
    }
  ],
  products: [
    {
      name: "vienna Red Dress",
      category: "dresses",
      image: "/images/p1.jpg",
      price: 79,
      countInStock: 10,
      brand: "vienna",
      rating: 4.5,
      numReviews: 13,
      description: "hight quality product",
    },
    {
      name: "h&m Black Dress",
      category: "dresses",
      image: "/images/p2.jpg",
      price: 49,
      countInStock: 0,
      brand: "h&m",
      rating: 3.5,
      numReviews: 12,
      description: "hight quality product",
    },
    {
      name: "zara Black Dress",
      category: "dresses",
      image: "/images/p3.jpg",
      price: 99,
      countInStock: 30,
      brand: "zara",
      rating: 4.0,
      numReviews: 7,
      description: "hight quality product",
    },
    {
      name: "terranova white Dress",
      category: "dresses",
      image: "/images/p4.jpg",
      price: 89,
      countInStock: 15,
      brand: "terranova",
      rating: 4.5,
      numReviews: 18,
      description: "hight quality product",
    },
    {
      name: "vienna white Dress",
      category: "dresses",
      image: "/images/p5.jpg",
      price: 79,
      countInStock: 5,
      brand: "vienna",
      rating: 5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      name: "zara Red Dress",
      category: "dresses",
      image: "/images/p6.jpg",
      price: 129,
      countInStock: 1,
      brand: "zara",
      rating: 5,
      numReviews: 12,
      description: "hight quality product",
    },
    {
      name: "motivie Red Dress",
      category: "dresses",
      image: "/images/p7.jpg",
      price: 49,
      countInStock: 6,
      brand: "motivie",
      rating: 3.0,
      numReviews: 15,
      description: "hight quality product",
    },
  ],
};

export default data;
